package eaf.core.entities.maad;

// Generated Jun 21, 2011 9:27:57 AM by Hibernate Tools 3.4.0.Beta1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import eaf.core.common.GlobalVars;
import eaf.core.entities.PersistentEntity;
import eaf.core.entities.pub.SctyClass;

/**
 * Ia generated by hbm2java
 */
public class Ia extends PersistentEntity implements java.io.Serializable {

    public Ia(final GlobalVars gVars) {
        super(gVars);
    }

    private String                iaId;
    private SoftitemCotscd        softitemCotscd;
    private IaReusecd             iaReusecd;
    private SoftitemSubcatcd      softitemSubcatcd;
    private SoftitemGotscd        softitemGotscd;
    private Softitemtype          softitemtype;
    private SoftitemMilcompllvlcd softitemMilcompllvlcd;
    private Fa                    fa;
    private Serializable          owner;
    private Serializable          datetime;
    private int                   archive;
    private String                iaAcronym;
    private String                iaCertstatus;
    private String                iaComment;
    private String                iaDefinition;
    private String                iaNm;
    private Integer               iaRfsnum;
    private String                iaSnm;
    private Date                  iaStdstatuscaldate;
    private String                iaVersionid;
    private SctyClass             scCd;
    private String                iaCmdDispCd;
    private String                iaFamDispCd;
    private String                iaDadmsId;
    private String                iaProgramOfRecord;
    private String                iaMigrationPlans;
    private String                iaUrl;
    private int                   iaArchive;
    private Integer               pocId;
    private Date                  iaLda;
    private String                iaBuildid;
    private Integer               iaCompliancecd;
    private String                iaDiskreq;
    private Integer               iaElocqty;
    private String                iaInternExtern;
    private Integer               iaMaxsimiluserqty;
    private String                iaUsexml;
    private String                iaVerchngcomment;
    private String                iaVersid;
    private String                iaSrclng;
    private String                iaOsrequired;
    private String                iaWillusexml;
    private String                iaProdstatuscd;
    private String                iaDesc;
    private Date                  iaVersionrelease;
    private String                iaSubtype;
    private Set<PociaAssoc>       pociaAssocs = new HashSet<PociaAssoc>(0);

    public Ia() {
    }

    public Ia(String iaId, IaReusecd iaReusecd, Fa fa, int archive, String iaDefinition, String iaNm, String iaSnm,
            String iaVersionid, SctyClass scCd) {
        this.iaId = iaId;
        this.iaReusecd = iaReusecd;
        this.fa = fa;
        this.archive = archive;
        this.iaDefinition = iaDefinition;
        this.iaNm = iaNm;
        this.iaSnm = iaSnm;
        this.iaVersionid = iaVersionid;
        this.scCd = scCd;

    }

    public Ia(String iaId, SoftitemCotscd softitemCotscd, IaReusecd iaReusecd, SoftitemSubcatcd softitemSubcatcd,
            SoftitemGotscd softitemGotscd, Softitemtype softitemtype, SoftitemMilcompllvlcd softitemMilcompllvlcd,
            Fa fa, Serializable owner, Serializable datetime, String iaAcronym, String iaCertstatus, String iaComment,
            String iaDefinition, String iaNm, Integer iaRfsnum, String iaSnm, Date iaStdstatuscaldate,
            String iaVersionid, SctyClass scCd, String iaCmdDispCd, String iaFamDispCd, String iaDadmsId,
            String iaProgramOfRecord, String iaMigrationPlans, String iaUrl, Integer pocId, Date iaLda,
            String iaBuildid, Integer iaCompliancecd, String iaDiskreq, Integer iaElocqty, String iaInternExtern,
            Integer iaMaxsimiluserqty, String iaUsexml, String iaVerchngcomment, String iaVersid, String iaSrclng,
            String iaOsrequired, String iaWillusexml, String iaProdstatuscd, String iaDesc, Date iaVersionrelease,
            String iaSubtype, Set<PociaAssoc> pociaAssocs) {
        this.iaId = iaId;
        this.softitemCotscd = softitemCotscd;
        this.iaReusecd = iaReusecd;
        this.softitemSubcatcd = softitemSubcatcd;
        this.softitemGotscd = softitemGotscd;
        this.softitemtype = softitemtype;
        this.softitemMilcompllvlcd = softitemMilcompllvlcd;
        this.fa = fa;
        this.owner = owner;
        this.datetime = datetime;
        this.archive = archive;
        this.pocId = pocId;
        this.iaAcronym = iaAcronym;
        this.iaCertstatus = iaCertstatus;
        this.iaComment = iaComment;
        this.iaDefinition = iaDefinition;
        this.iaNm = iaNm;
        this.iaRfsnum = iaRfsnum;
        this.iaSnm = iaSnm;
        this.iaStdstatuscaldate = iaStdstatuscaldate;
        this.iaVersionid = iaVersionid;
        this.scCd = scCd;
        this.iaCmdDispCd = iaCmdDispCd;
        this.iaFamDispCd = iaFamDispCd;
        this.iaDadmsId = iaDadmsId;
        this.iaProgramOfRecord = iaProgramOfRecord;
        this.iaMigrationPlans = iaMigrationPlans;
        this.iaUrl = iaUrl;
        this.iaLda = iaLda;
        this.iaBuildid = iaBuildid;
        this.iaCompliancecd = iaCompliancecd;
        this.iaDiskreq = iaDiskreq;
        this.iaElocqty = iaElocqty;
        this.iaInternExtern = iaInternExtern;
        this.iaMaxsimiluserqty = iaMaxsimiluserqty;
        this.iaUsexml = iaUsexml;
        this.iaVerchngcomment = iaVerchngcomment;
        this.iaVersid = iaVersid;
        this.iaSrclng = iaSrclng;
        this.iaOsrequired = iaOsrequired;
        this.iaWillusexml = iaWillusexml;
        this.iaProdstatuscd = iaProdstatuscd;
        this.iaDesc = iaDesc;
        this.iaVersionrelease = iaVersionrelease;
        this.iaSubtype = iaSubtype;
        this.pociaAssocs = pociaAssocs;
    }

    public String getIaId() {
        return this.iaId;
    }

    public void setIaId(String iaId) {
        this.iaId = iaId;
    }

    public SoftitemCotscd getSoftitemCotscd() {
        return this.softitemCotscd;
    }

    public void setSoftitemCotscd(SoftitemCotscd softitemCotscd) {
        this.softitemCotscd = softitemCotscd;
    }

    public IaReusecd getIaReusecd() {
        return this.iaReusecd;
    }

    public void setIaReusecd(IaReusecd iaReusecd) {
        this.iaReusecd = iaReusecd;
    }

    public SoftitemSubcatcd getSoftitemSubcatcd() {
        return this.softitemSubcatcd;
    }

    public void setSoftitemSubcatcd(SoftitemSubcatcd softitemSubcatcd) {
        this.softitemSubcatcd = softitemSubcatcd;
    }

    public SoftitemGotscd getSoftitemGotscd() {
        return this.softitemGotscd;
    }

    public void setSoftitemGotscd(SoftitemGotscd softitemGotscd) {
        this.softitemGotscd = softitemGotscd;
    }

    public Softitemtype getSoftitemtype() {
        return this.softitemtype;
    }

    public void setSoftitemtype(Softitemtype softitemtype) {
        this.softitemtype = softitemtype;
    }

    public SoftitemMilcompllvlcd getSoftitemMilcompllvlcd() {
        return this.softitemMilcompllvlcd;
    }

    public void setSoftitemMilcompllvlcd(SoftitemMilcompllvlcd softitemMilcompllvlcd) {
        this.softitemMilcompllvlcd = softitemMilcompllvlcd;
    }

    public Fa getFa() {
        return this.fa;
    }

    public void setFa(Fa fa) {
        this.fa = fa;
    }

    public String getOwner() {
        return (String) this.owner;
    }

    public void setOwner(Serializable owner) {
        this.owner = owner;
    }

    public Date getDatetime() {
        return (Date) this.datetime;
    }

    public void setDatetime(Serializable datetime) {
        this.datetime = datetime;
    }

    public int getArchive() {
        return (Integer) this.archive;
    }

    public void setArchive(int archive) {
        this.archive = archive;
    }

    public Integer getPocId() {
        return this.pocId;
    }

    public void setPocId(Integer pocId) {
        this.pocId = pocId;
    }

    public String getIaAcronym() {
        return this.iaAcronym;
    }

    public void setIaAcronym(String iaAcronym) {
        this.iaAcronym = iaAcronym;
    }

    public String getIaCertstatus() {
        return this.iaCertstatus;
    }

    public void setIaCertstatus(String iaCertstatus) {
        this.iaCertstatus = iaCertstatus;
    }

    public String getIaComment() {
        return this.iaComment;
    }

    public void setIaComment(String iaComment) {
        this.iaComment = iaComment;
    }

    public String getIaDefinition() {
        return this.iaDefinition;
    }

    public void setIaDefinition(String iaDefinition) {
        this.iaDefinition = iaDefinition;
    }

    public String getIaNm() {
        return this.iaNm;
    }

    public void setIaNm(String iaNm) {
        this.iaNm = iaNm;
    }

    public Integer getIaRfsnum() {
        return this.iaRfsnum;
    }

    public void setIaRfsnum(Integer iaRfsnum) {
        this.iaRfsnum = iaRfsnum;
    }

    public String getIaSnm() {
        return this.iaSnm;
    }

    public void setIaSnm(String iaSnm) {
        this.iaSnm = iaSnm;
    }

    public Date getIaStdstatuscaldate() {
        return this.iaStdstatuscaldate;
    }

    public void setIaStdstatuscaldate(Date iaStdstatuscaldate) {
        this.iaStdstatuscaldate = iaStdstatuscaldate;
    }

    public String getIaVersionid() {
        return this.iaVersionid;
    }

    public void setIaVersionid(String iaVersionid) {
        this.iaVersionid = iaVersionid;
    }

    public SctyClass getScCd() {
        return this.scCd;
    }

    public void setScCd(SctyClass scCd) {
        this.scCd = scCd;
    }

    public String getIaCmdDispCd() {
        return this.iaCmdDispCd;
    }

    public void setIaCmdDispCd(String iaCmdDispCd) {
        this.iaCmdDispCd = iaCmdDispCd;
    }

    public String getIaFamDispCd() {
        return this.iaFamDispCd;
    }

    public void setIaFamDispCd(String iaFamDispCd) {
        this.iaFamDispCd = iaFamDispCd;
    }

    public String getIaDadmsId() {
        return this.iaDadmsId;
    }

    public void setIaDadmsId(String iaDadmsId) {
        this.iaDadmsId = iaDadmsId;
    }

    public String getIaProgramOfRecord() {
        return this.iaProgramOfRecord;
    }

    public void setIaProgramOfRecord(String iaProgramOfRecord) {
        this.iaProgramOfRecord = iaProgramOfRecord;
    }

    public String getIaMigrationPlans() {
        return this.iaMigrationPlans;
    }

    public void setIaMigrationPlans(String iaMigrationPlans) {
        this.iaMigrationPlans = iaMigrationPlans;
    }

    public String getIaUrl() {
        return this.iaUrl;
    }

    public void setIaUrl(String iaUrl) {
        this.iaUrl = iaUrl;
    }

    public int getIaArchive() {
        return this.iaArchive;
    }

    public void setIaArchive(int iaArchive) {
        this.iaArchive = iaArchive;
    }

    public Date getIaLda() {
        return this.iaLda;
    }

    public void setIaLda(Date iaLda) {
        this.iaLda = iaLda;
    }

    public String getIaBuildid() {
        return this.iaBuildid;
    }

    public void setIaBuildid(String iaBuildid) {
        this.iaBuildid = iaBuildid;
    }

    public Integer getIaCompliancecd() {
        return this.iaCompliancecd;
    }

    public void setIaCompliancecd(Integer iaCompliancecd) {
        this.iaCompliancecd = iaCompliancecd;
    }

    public String getIaDiskreq() {
        return this.iaDiskreq;
    }

    public void setIaDiskreq(String iaDiskreq) {
        this.iaDiskreq = iaDiskreq;
    }

    public Integer getIaElocqty() {
        return this.iaElocqty;
    }

    public void setIaElocqty(Integer iaElocqty) {
        this.iaElocqty = iaElocqty;
    }

    public String getIaInternExtern() {
        return this.iaInternExtern;
    }

    public void setIaInternExtern(String iaInternExtern) {
        this.iaInternExtern = iaInternExtern;
    }

    public Integer getIaMaxsimiluserqty() {
        return this.iaMaxsimiluserqty;
    }

    public void setIaMaxsimiluserqty(Integer iaMaxsimiluserqty) {
        this.iaMaxsimiluserqty = iaMaxsimiluserqty;
    }

    public String getIaUsexml() {
        return this.iaUsexml;
    }

    public void setIaUsexml(String iaUsexml) {
        this.iaUsexml = iaUsexml;
    }

    public String getIaVerchngcomment() {
        return this.iaVerchngcomment;
    }

    public void setIaVerchngcomment(String iaVerchngcomment) {
        this.iaVerchngcomment = iaVerchngcomment;
    }

    public String getIaVersid() {
        return this.iaVersid;
    }

    public void setIaVersid(String iaVersid) {
        this.iaVersid = iaVersid;
    }

    public String getIaSrclng() {
        return this.iaSrclng;
    }

    public void setIaSrclng(String iaSrclng) {
        this.iaSrclng = iaSrclng;
    }

    public String getIaOsrequired() {
        return this.iaOsrequired;
    }

    public void setIaOsrequired(String iaOsrequired) {
        this.iaOsrequired = iaOsrequired;
    }

    public String getIaWillusexml() {
        return this.iaWillusexml;
    }

    public void setIaWillusexml(String iaWillusexml) {
        this.iaWillusexml = iaWillusexml;
    }

    public String getIaProdstatuscd() {
        return this.iaProdstatuscd;
    }

    public void setIaProdstatuscd(String iaProdstatuscd) {
        this.iaProdstatuscd = iaProdstatuscd;
    }

    public String getIaDesc() {
        return this.iaDesc;
    }

    public void setIaDesc(String iaDesc) {
        this.iaDesc = iaDesc;
    }

    public Date getIaVersionrelease() {
        return this.iaVersionrelease;
    }

    public void setIaVersionrelease(Date iaVersionrelease) {
        this.iaVersionrelease = iaVersionrelease;
    }

    public String getIaSubtype() {
        return this.iaSubtype;
    }

    public void setIaSubtype(String iaSubtype) {
        this.iaSubtype = iaSubtype;
    }

    @Override
    public String getId() {
        return getIaId();

    }

    @Override
    public String getName() {
        return getIaNm();
    }

    @Override
    public final void setId(final Object id) {
        this.setIaId((String) id);
    }

    @Override
    public final void setName(final String incName) {
        this.setIaNm(incName);
    }

    public Set<PociaAssoc> getPociaAssoc() {
        return this.pociaAssocs;
    }

    public void setPociaAssoc(Set<PociaAssoc> pociaAssocs) {
        this.pociaAssocs = pociaAssocs;
    }

}
