package eaf.core.entities.jmcms;

// Generated Feb 4, 2011 12:59:02 PM by Hibernate Tools 3.4.0.Beta1

import eaf.core.entities.PersistentEntity;
import eaf.core.common.GlobalVars;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MplParam generated by hbm2java
 */
public class MplParam extends PersistentEntity implements java.io.Serializable {

    private int           mplIaId;
    private String        camelcaseuom;
    private String        abbrev;
    private String        afwaGribParameterNumber;
    private String        fnmocGribParameterNumber;
    private String        ncepGribParameterNumber;
    private Integer       navoParameter;
    private String        interpolationMethod;
    private Integer       compoundFlag;
    private String        compoundBusinessRule;
    private String        parameterSource;
    private String        definitionSource;
    private String        domainCd;
    private Integer       deprecatedFlg;
    private String        mplParamNm;
    private String        uom;
    private InfoAsset     infoAsset;
    private Set<MapAssoc> mapAssocs = new HashSet<MapAssoc>(0);

    public MplParam() {
    }

    public MplParam(final GlobalVars gVars) {
        super(gVars);
    }

    public MplParam(final int incMplIaId, final int incArchive) {
        mplIaId = incMplIaId;
    }

    public MplParam(int incMplIaId, String incOwner, Date incDatetime, int incArchive, String incCamelcaseuom,
            String incAbbrev, String incAfwaGribParameterNumber, String incFnmocGribParameterNumber,
            String incNcepGribParameterNumber, Integer incNavoParameter, String incInterpolationMethod,
            Integer incCompoundFlag, String incCompoundBusinessRule, String incParameterSource,
            String incDefinitionSource, String incDomainCd, Integer incDeprecatedFlg, String incMplParamNm,
            String incUom) {
        mplIaId = incMplIaId;
        camelcaseuom = incCamelcaseuom;
        abbrev = incAbbrev;
        afwaGribParameterNumber = incAfwaGribParameterNumber;
        fnmocGribParameterNumber = incFnmocGribParameterNumber;
        ncepGribParameterNumber = incNcepGribParameterNumber;
        navoParameter = incNavoParameter;
        interpolationMethod = incInterpolationMethod;
        compoundFlag = incCompoundFlag;
        compoundBusinessRule = incCompoundBusinessRule;
        parameterSource = incParameterSource;
        definitionSource = incDefinitionSource;
        domainCd = incDomainCd;
        deprecatedFlg = incDeprecatedFlg;
        mplParamNm = incMplParamNm;
        uom = incUom;
    }

    public int getMplIaId() {
        return this.mplIaId;
    }

    public void setMplIaId(final int incMplIaId) {
        mplIaId = incMplIaId;
    }

    public String getCamelcaseuom() {
        return this.camelcaseuom;
    }

    public void setCamelcaseuom(final String incCamelcaseuom) {
        camelcaseuom = incCamelcaseuom;
    }

    public String getAbbrev() {
        return this.abbrev;
    }

    public void setAbbrev(final String incAbbrev) {
        abbrev = incAbbrev;
    }

    public String getAfwaGribParameterNumber() {
        return this.afwaGribParameterNumber;
    }

    public void setAfwaGribParameterNumber(final String incAfwaGribParameterNumber) {
        afwaGribParameterNumber = incAfwaGribParameterNumber;
    }

    public String getFnmocGribParameterNumber() {
        return this.fnmocGribParameterNumber;
    }

    public void setFnmocGribParameterNumber(final String incFnmocGribParameterNumber) {
        fnmocGribParameterNumber = incFnmocGribParameterNumber;
    }

    public String getNcepGribParameterNumber() {
        return this.ncepGribParameterNumber;
    }

    public void setNcepGribParameterNumber(final String incNcepGribParameterNumber) {
        ncepGribParameterNumber = incNcepGribParameterNumber;
    }

    public Integer getNavoParameter() {
        return this.navoParameter;
    }

    public void setNavoParameter(final Integer incNavoParameter) {
        navoParameter = incNavoParameter;
    }

    public String getInterpolationMethod() {
        return this.interpolationMethod;
    }

    public void setInterpolationMethod(final String incInterpolationMethod) {
        interpolationMethod = incInterpolationMethod;
    }

    public Integer getCompoundFlag() {
        return this.compoundFlag;
    }

    public void setCompoundFlag(final Integer incCompoundFlag) {
        compoundFlag = incCompoundFlag;
    }

    public String getCompoundBusinessRule() {
        return this.compoundBusinessRule;
    }

    public void setCompoundBusinessRule(final String incCompoundBusinessRule) {
        compoundBusinessRule = incCompoundBusinessRule;
    }

    public String getParameterSource() {
        return this.parameterSource;
    }

    public void setParameterSource(final String incParameterSource) {
        parameterSource = incParameterSource;
    }

    public String getDefinitionSource() {
        return this.definitionSource;
    }

    public void setDefinitionSource(final String incDefinitionSource) {
        definitionSource = incDefinitionSource;
    }

    public String getDomainCd() {
        return this.domainCd;
    }

    public void setDomainCd(final String incDomainCd) {
        domainCd = incDomainCd;
    }

    public Integer getDeprecatedFlg() {
        return this.deprecatedFlg;
    }

    public void setDeprecatedFlg(final Integer incDeprecatedFlg) {
        deprecatedFlg = incDeprecatedFlg;
    }

    public String getMplParamNm() {
        return this.mplParamNm;
    }

    public void setMplParamNm(final String incMplParamNm) {
        mplParamNm = incMplParamNm;
    }

    public String getUom() {
        return this.uom;
    }

    public void setUom(final String incUom) {
        uom = incUom;
    }

    @Override
    public Integer getId() {
        return this.getMplIaId();
    }

    @Override
    public void setId(final Object id) {
        this.setMplIaId(((Integer) id).intValue());
    }

    public InfoAsset getInfoAsset() {
        return this.infoAsset;
    }

    public void setInfoAsset(final InfoAsset incMplIaId) {
        infoAsset = incMplIaId;
    }

    @Override
    public String getName() {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public void setName(String incName) {
        // TODO Auto-generated method stub

    }

    public Set<MapAssoc> getMapAssocs() {
        return this.mapAssocs;
    }

    public void setMapAssocs(final Set<MapAssoc> incMapAssocs) {
        this.mapAssocs = incMapAssocs;
    }
}
